# Shopify App config (prod + dev)
client_id = "8b7905126e30769a20c27b4cdd775722"
name = "refina"
handle = "refina"

# The embedded Admin entry — our backend serves /embedded → /admin-ui
application_url = "https://refina-shopify-app.onrender.com/embedded"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "refina-demo.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
scopes = "read_products"

# OAuth callback(s). Keep dev ngrok + prod Render so either works.
[auth]
redirect_urls = [
  "https://refina-shopify-app.onrender.com/api/auth/callback",
  "https://refina.ngrok.app/api/auth/callback"
]

# ✅ App Proxy mapping used by the storefront to load /apps/refina/*
[app_proxy]
prefix = "apps"
subpath = "refina"
url = "https://refina-shopify-app.onrender.com/proxy/refina"
