# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8b7905126e30769a20c27b4cdd775722"
name = "refina"
handle = "refina"

application_url = "https://refina-app.onrender.com/embedded"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "refina-demo.myshopify.com"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = ["customers/data_request"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = ["customers/redact"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = ["shop/redact"]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/products"
  topics = ["products/create"]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/products"
  topics = ["products/update"]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/products"
  topics = ["products/delete"]

[access_scopes]
scopes = "read_products"


[auth]
redirect_urls = [
  "https://refina-app.onrender.com/api/auth/callback",
  "https://refina-app.onrender.com/auth/callback"
]

[app_proxy]
url = "https://refina-app.onrender.com/proxy/refina"
subpath = "refina"
prefix = "apps"

[pos]
embedded = false
